---
title: "Publications"
---

<br>

## 2021
**Pedersen, C. B.**, **Dam, S. H.**, Barnkob, M. B., Leipold, M. D., Purroy, N., Rassenti, L. Z., Kipps, T. J., Nguyen, J., Lederer, J. A., Gohil, S. H., Wu, C. J., **Olsen, L. R.** (2021). Robust integration of single-cell cytometry datasets. *bioRxiv*. [doi:10.1101/2021.06.28.450128](https://doi.org/10.1101/2021.06.28.450128)

Barnkob, M. B., Benso, A., Politano, G., **Olsen L. R.** (2021). Spectracular: minimizing spectral overlap in multicolor flow cytometry experiments. *bioRxiv*. [doi:10.1101/2021.03.17.435861](https://doi.org/10.1101/2021.03.17.435861)

Rossing, M., **Pedersen, C. B.**, Tvedskov, T., Vejborg, I., Talman, M. L., **Olsen, L. R.**, Kroman, N., Nielsen, F. C., Jensen, M. B., & Ejlertsen, B. (2021). Clinical implications of intrinsic molecular subtypes of breast cancer for sentinel node status. *Scientific Reports, 11(1), [2259]*. [doi:10.1038/s41598-021-81538-4](https://doi.org/10.1038/s41598-021-81538-4)

Kretzmer, H., Biran, A., Purroy, N., **Lemvigh, C. K.**, Clement, K., Gruber, M., Gu, H., Rassenti, L., Mohammad, A. W., Lesnick, C., Slager, S. L., Braggio, E., Shanafelt, T. D., Kay, N. E., Fernandes, S., Brown, J. R., Wang, L., Li, S., Livak, K. J., Neuberg, D. S., Klages, S., Timmermann, B., Kipps, T. J., Campo, E., Gnirke, A., Wu, C. J., & Meissner, A. (2021). Preneoplastic alterations define CLL DNA methylome and persist through disease progression and therapy. *Blood cancer discovery, 2(1), 54.* [doi:10.1158/2643-3230.BCD-19-0058](https://doi.org/10.1158/2643-3230.BCD-19-0058)

Braun, D. A., Street, K., Burke, K. P., Cookmeyer, D. L., Denize, T., **Pedersen, C. B.**, Gohil, S. H., Schindler, N,, Pomerance, L., Hirsch, L., Bakouny, Z., Hou, Y., Forman, J., Huang, T., Li, S., Cui, A., Keskin, D. B., Steinharter, J., Bouchard, G., Sun, M., Pimenta, E. M., Xu, W., Mahoney, K. M., McGregor, B. A., Hirsch, M. S., Chang, S. L., Livak, K. J., McDermott, D. F., Shukla, S. A., **Olsen, L. R.**, Signoretti, S., Sharpe, A. H., Irizarry, R. A., Choueiri, T. K., Wu, C. J. (2021). Progressive immune dysfunction with advancing disease stage in renal cell carcinoma. *Cancer Cell.* [doi:10.1016/j.ccell.2021.02.013](https://doi.org/10.1016/j.ccell.2021.02.013)

Crump, N. T., Hadjinicolaou, A. V., Xia, M., Walsby-Tickle, J., Gileadi, U., Chen, J. L., Setshedi, M., **Olsen, L. R.**, Lau, I. J., Godfrey, L. Quek, L., Yu, Z., Ballabio, E., Barnkob, M. B., Napolitani, G., Salio, M., Koohy, H., Kessler, B. M., Taylor, S., Vyas, P., McCullagh, J. S. O., Milne, T. A., Cerundolo, V. (2021). Chromatin accessibility governs the differential response of cancer and T cells to arginine starvation. *Cell reports, 35(6), p.109101*. [doi:10.1016/j.celrep.2021.109101](https://doi.org/10.1016/j.celrep.2021.109101)

Choudry, F. A., Bagger, F. O., Macaulay, I. C., Farrow, S., Burden, F., Kempster, C., McKinney, H., **Olsen, L. R.**, Huang, N., Downes, K., Voet, T., Uppal, R., Martin, J. F., Mathur, A., Ouwehand, W. H., Laurenti, E., Teichmann, S. A., & Frontini, M. (2021). Transcriptional characterization of human megakaryocyte polyploidization and lineage commitment. *Journal of Thrombosis and Haemostasis*. [doi:10.1111/jth.15271](https://doi.org/10.1111/jth.15271)

Hu, Z., Leet, D. E., Allesøe, R. L., Oliveira, G., Li, S., Luoma, A. M., Liu, J., Forman, J., Huang, T., Iorgulescu, J. B., Holden, R., Sarkizova, S., Gohil, S. H., Redd, R. A., Sun, J., Elagina, L., Giobbie-Hurder, A., Zhang, W., Peter, L., Ciantra, Z., Rodig, S., Olive, O., Shetty, K., Pyrdol, J., Uduman, M., Lee, P. C., Bachireddy, P., Buchbinder, E. I., Yoon, C. H., Neuberg, D., Pentelute, B. L., Hacohen, N., Livak, K. J., Shukla, S. A., **Olsen, L. R.**, Barouch, D. H.,  Wucherpfennig, K. W, Fritsch, E. F., Keskin, D. B., Wu, C. J., & Ott, P. A. (2021). Personal neoantigen vaccines induce persistent memory T cell responses and epitope spreading in patients with melanoma. *Nature Medicine, 1-11.* [doi:10.1038/s41591-020-01206-4](https://doi.org/10.1038/s41591-020-01206-4)

<br><br>


## 2020
**Pedersen, C. B.**, & **Olsen, L. R.** (2020). Algorithmic Clustering Of Single‐Cell Cytometry Data—How Unsupervised Are These Analyses Really?. *Cytometry Part A.* [doi:10.1002/cyto.a.23917](https://doi.org/10.1002/cyto.a.23917)

Kverneland, A. H., Pedersen, M., Westergaard, M. C. W., Nielsen, M., Borch, T. H., **Olsen, L. R.**, **Aasbjerg, G.**, Santegoets, S. J., van der Burg, S. H., Milne, K., Nelson, B. H., Met, Ö., Donia, M., & Svane, I. M. (2020). Adoptive cell therapy in combination with checkpoint inhibitors in ovarian cancer. *OncoTarget, 11(22), 2092-2105*. [doi:10.18632/oncotarget.27604](https://doi.org/10.18632/oncotarget.27604)

Westergaard, M. C. W., Milne, K., Pedersen, M., Hasselager, T., **Olsen, L. R.**, Anglesio, M. S., Borch, T. H., Kennedy, M., Briggs, G., Ledoux, S., Kreuzinger, C., von der Decken, I., Donia, M., Castillo-Tong, D. C., Nelson, B. H., & Svane, I. M. (2020). Changes in the tumor immune microenvironment during disease progression in patients with ovarian cancer. *Cancers, 12(12), [3828]*. [doi:10.3390/cancers12123828](https://doi.org/10.3390/cancers12123828)

Jørgensen, N. G., Klausen, U., Grauslund, J. H., Helleberg, C., Aagaard, T. G., Do, T. H., Ahmad, S. M., **Olsen, L. R.**, Klausen, T. W., Breinholt, M. F., Hansen, M., Martinenaite, E., Met, Ö., Svane, I. M., Knudsen, L. M., & Andersen, M. H. (2020). Peptide Vaccination Against PD-L1 With IO103 a Novel Immune Modulatory Vaccine in Multiple Myeloma: A Phase I First-in-Human Trial. *Frontiers in Immunology, 11, [595035]*. [doi:10.3389/fimmu.2020.595035](https://doi.org/10.3389/fimmu.2020.595035)

<br><br>



## 2019
**Pedersen, C. B.**, & **Olsen, L. R.** (2019). Analysis of Mass Cytometry Data. In Mass Cytometry (pp. 267-279). *Humana, New York, NY.* [doi:10.1007/978-1-4939-9454-0_17](https://doi.org/10.1007/978-1-4939-9454-0_17)

Simon, C., Davidsen, K., **Hansen, C.**, Seymour, E., Barnkob, M. B., & **Olsen, L. R.** (2019). BioReader: a text mining tool for performing classification of biomedical literature. *BMC bioinformatics, 19(13), 57.* [doi:10.1186/s12859-019-2607-x](https://doi.org/10.1186/s12859-019-2607-x)

Jurtz, V. I., & **Olsen, L. R.** (2019). Computational methods for identification of T cell neoepitopes in tumors. In Cancer Bioinformatics (pp. 157-172). Humana Press, New York, NY. [doi:10.1007/978-1-4939-8868-6_9](https://doi.org/10.1007/978-1-4939-8868-6_9)

**Olsen, L. R.**, **Pedersen, C. B.**, Leipold, M. D., & Maecker, H. T. (2019). Getting the Most from Your High-Dimensional Cytometry Data. *Immunity, 50(3), 535-536.* [doi:10.1016/j.immuni.2019.02.015](https://doi.org/10.1016/j.immuni.2019.02.015)

Li, S., Sun, J., **Allesøe, R.**, Datta, K., Bao, Y., Oliveira, G., Forman, J., Jin, R., **Olsen, L. R.**, Keskin, D. B., Shukla, S. A., Wu, C. J. & Livak, K. J. (2019). RNase H–dependent PCR-enabled T-cell receptor sequencing for highly specific and efficient targeted sequencing of T-cell receptor mRNA for single-cell and repertoire analysis. *Nature protocols, 14(8), 2571-2594.* [doi:10.1038/s41596-019-0195-x](https://doi.org/10.1038/s41596-019-0195-x)

**Olsen, L. R.**, Leipold, M. D., **Pedersen, C. B.**, & Maecker, H. T. (2019). The anatomy of single cell mass cytometry data. *Cytometry Part A, 95(2), 156-172.* [doi:10.1002/cyto.a.23621](https://doi.org/10.1002/cyto.a.23621)

Keskin, D. B., Anandappa, A. J., Sun, J., Tirosh, I., Mathewson, N. D., Li, S., Oliveira, G., Giobbie-Hurder, A., Felt, K., Gjini, E., Shukla, S. A., Hu, Z., Li, L., Le, P. M., **Allesøe, R. L.**, Richman, A. R., Kowalczyk, M. S., Abdelrahman, S., Geduldig, J. E., Charbonneau, S., Pelton, K., Iorgulescu, J. B., Elagina, L., Zhang, W., Olive, O., McCluskey, C., **Olsen, L. R.**, Stevens, J., Lane, W. J., Salazar, A. M., Daley, H., Wen, P .Y., Chiocca, E. A., Harden, M., Lennon, N. J., Gabriel, S., Getz, G., Lander, E. S., Regev, A., Ritz, J., Neuberg, D., Rodig, S. J., Ligon, K. L., Suvà, M. L., Wucherpfennig, K. W., Hacohen, N., Fritsch, E. F., Livak, K. J., Ott, P. A., Wu, C. J., Reardon, D. A. (2018). Neoantigen vaccine generates intratumoral T cell responses in phase Ib glioblastoma trial. *Nature, 565, 234-239*. [doi:10.1038/s41586-018-0792-9](https://doi.org/10.1038/s41586-018-0792-9)

<br><br>



## 2018
Napolitani, G., Kurupati, P., Teng, K. W. W., Gibani, M. M., Rei, M., Aulicino, A., Preciado-Llanes, L., Wong, M. T.; Becht, E., Howson, L., de Haas, P., Salio, M., Blohmke, C. J., **Olsen, L. R.**, Pinto, D. M. S., Scifo, L., Jones, C., Dobinson, H. Campbell, D., Juel, H. B., Thomaides-Brears, H., Pickard, D., Bumann, D., Baker, S., Dougan, G., Simmons, A., Gordon, M. A., Newell, E. W., Pollard, A. J. & Cerundolo, Vincenzo (2018). Clonal analysis of Salmonella-specific effector T cells reveals serovar-specific and cross-reactive T cell responses. *Nature immunology, 19(7), 742-754.* [doi:10.1038/s41590-018-0133-z](https://doi.org/10.1038/s41590-018-0133-z)

Leipold, M. D., Obermoser, G., Fenwick, C., Kleinstuber, K., Rashidi, N., McNevin, J. P., Nau, A. N., Wagar, L. E., Rozot, V., Davis, M. M., DeRosa, S., Pantaleo, G., Scriba, T. J., Walker, B. D., **Olsen, L. R.** & Maecker, H. T. (2018). Comparison of CyTOF assays across sites: Results of a six-center pilot study. *Journal of immunological methods, 453, 37-43.* [doi:10.1016/j.jim.2017.11.008](https://doi.org/10.1016/j.jim.2017.11.008)

**Pedersen, C. B.**, Nielsen, F. C., Rossing, M., & **Olsen, L. R.** (2018). Using microarray‐based subtyping methods for breast cancer in the era of high‐throughput RNA sequencing. *Molecular oncology, 12(12), 2136-2146.* [doi:10.1002/1878-0261.12389](https://doi.org/10.1002/1878-0261.12389)
