---
title: "ALPP"

knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_format = "html_document",
      output_dir = "../results/html_docs",
    )
  })
---
<style>
img {
    max-width: 30cm;

}
</style>

```{r, eval = TRUE, echo = FALSE, warning = FALSE, message = FALSE}
setwd("../../")
source("cartcontent/scr/00_functions.R")
```

<h4>Description</h4>
Alkaline phosphatase, placental type ([ALPP](https://www.uniprot.org/uniprot/P05187)). 

<br> 

<h4>Clinical trials</h4>
[NCT04627740](https://clinicaltrials.gov/ct2/show/NCT04627740) - Ovarian Cancer, Endometrial Cancer

<br>

<h4>Target gene expression</h4>
```{r, eval = TRUE, echo = FALSE, warning = FALSE, message = F, fig.width = 32, fig.height= 20}
setwd("../../")
boxplot_isoforms_all_tissues(hgnc = "ALPP") # it creates the boxplot in the html and saves it as .pdf in the plot/isoform_expression folder
```

<br>

<h4>Target essentiality</h4>

<br>

<h4>Protein properties</h4>
```{r, eval = TRUE, echo = FALSE, warning = FALSE, message = F, fig.width = 10, fig.height= 4}
setwd("../../")
plot_function("ALPP") # it creates the plot in the html and saves it as .pdf in the plot/protein_properties folder
```

