---
title: "MS4A1"

knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_format = "html_document",
      output_dir = "../results/html_docs",
    )
  })
---

```{r, eval = TRUE, echo = FALSE, warning = FALSE, message = FALSE}
setwd("../../")
source("cartcontent/scr/00_functions.R")
```

<br>

#### Description
B-lymphocyte antigen CD20 ([MS4A1](https://www.uniprot.org/uniprot/P11836)). B-lymphocyte-specific membrane protein that plays a role in the regulation of cellular calcium influx necessary for the development, differentiation, and activation of B-lymphocytes.
<br> 

#### Clinical trials 
[NCT03893019](https://clinicaltrials.gov/ct2/show/NCT03893019) - Melanoma

<br>

#### Target gene expression
```{r, eval = TRUE, echo = FALSE, warning = FALSE, message = F, fig.width = 27, fig.height= 12}
setwd("../../")
boxplot_isoforms_all_tissues(hgnc = "MS4A1") # it creates the boxplot in the html and saves it as .pdf in the plot/isoform_expression folder
```
<br>

#### Target splice variants

<br>

#### Target essentiality

<br>

#### Protein properties
```{r, eval = TRUE, echo = FALSE, warning = FALSE, message = F, fig.width = 12, fig.height= 5}
setwd("../../")
plot_function("MS4A1") # it creates the plot in the html and saves it as .pdf in the plot/protein_properties folder
```